var userData =
{
login: "russpate",
id: 5562260,
avatar_url: "https://avatars.githubusercontent.com/u/5562260?v=3",
gravatar_id: "",
url: "https://api.github.com/users/russpate",
html_url: "https://github.com/russpate",
followers_url: "https://api.github.com/users/russpate/followers",
following_url: "https://api.github.com/users/russpate/following{/other_user}",
gists_url: "https://api.github.com/users/russpate/gists{/gist_id}",
starred_url: "https://api.github.com/users/russpate/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/russpate/subscriptions",
organizations_url: "https://api.github.com/users/russpate/orgs",
repos_url: "https://api.github.com/users/russpate/repos",
events_url: "https://api.github.com/users/russpate/events{/privacy}",
received_events_url: "https://api.github.com/users/russpate/received_events",
type: "User",
site_admin: false,
name: "Russ Pate",
company: null,
blog: "russpate.com",
location: null,
email: "russ@russpate.com",
hireable: true,
bio: null,
public_repos: 12,
public_gists: 0,
followers: 1,
following: 4,
created_at: "2013-09-28T03:35:00Z",
updated_at: "2016-02-15T18:20:32Z"
};
